# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KCMYwLxEXyEOt9hFi17rPMFlDe484Ktk
"""

import streamlit as st
import pickle
import numpy as np
from inference import predict_booking_status

st.title("Booking Hotel Prediction")

st.write("Isi data pemesanan hotel untuk prediksi status pembatalan:")

no_of_adults = st.number_input("Jumlah orang dewasa", min_value=1, value=2)
no_of_children = st.number_input("Jumlah anak", min_value=0, value=0)
no_of_weekend_nights = st.number_input("Malam akhir pekan", min_value=0, value=1)
no_of_week_nights = st.number_input("Malam weekdays", min_value=0, value=2)
type_of_meal_plan = st.selectbox("Paket makanan", ["Meal Plan 1", "Meal Plan 2", "Meal Plan 3", "Not Selected"])
required_car_parking_space = st.selectbox("Butuh parkir?", [0, 1])
room_type_reserved = st.selectbox("Jenis kamar", ['Room_Type 1', 'Room_Type 2', 'Room_Type 3', 'Room_Type 4'])
lead_time = st.number_input("Lead time (hari)", min_value=0, value=30)
arrival_year = st.selectbox("Tahun kedatangan", [2017])  # sesuaikan dengan data
arrival_month = st.selectbox("Bulan kedatangan", list(range(1,13)))
arrival_date = st.number_input("Tanggal kedatangan", min_value=1, max_value=31, value=1)
market_segment_type = st.selectbox("Segment pasar", ['Online', 'Offline', 'Corporate', 'Complementary'])
repeated_guest = st.selectbox("Pelanggan lama?", [0, 1])
no_of_previous_cancellations = st.number_input("Pembatalan sebelumnya", min_value=0, value=0)
no_of_previous_bookings_not_canceled = st.number_input("Booking sebelumnya (tidak dibatalkan)", min_value=0, value=1)
avg_price_per_room = st.number_input("Harga rata-rata kamar", min_value=0.0, value=100.0)
no_of_special_requests = st.number_input("Permintaan khusus", min_value=0, value=0)

if st.button("Predict"):
    input_data = [no_of_adults, no_of_children, no_of_weekend_nights, no_of_week_nights,
                  type_of_meal_plan, required_car_parking_space, room_type_reserved,
                  lead_time, arrival_year, arrival_month, arrival_date,
                  market_segment_type, repeated_guest, no_of_previous_cancellations,
                  no_of_previous_bookings_not_canceled, avg_price_per_room,
                  no_of_special_requests]

    prediction = predict_booking_status(input_data)

    if prediction == 1:
        st.error("Booking kemungkinan besar *dibatalkan*")
    else:
        st.success("Booking kemungkinan *tidak dibatalkan*")