# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DhO31vWnji_dNchYOjSVkif5tXF70Tna
"""

import streamlit as st
import pandas as pd
import pickle

@st.cache_resource
def load_model():
    with open("best_model_pipeline.pkl", "rb") as f:
        return pickle.load(f)

model = load_model()

st.set_page_config(page_title="Hotel Booking Prediction", layout="centered")
st.title("Hotel Booking Cancellation Prediction")

with st.form("booking_form"):
    no_of_adults = st.number_input("Number of Adults", min_value=0, value=2)
    no_of_children = st.number_input("Number of Children", min_value=0, value=0)
    no_of_weekend_nights = st.number_input("Weekend Nights", min_value=0, value=1)
    no_of_week_nights = st.number_input("Week Nights", min_value=0, value=2)
    type_of_meal_plan = st.text_input("Meal Plan (e.g. Meal Plan 1)")
    required_car_parking_space = st.number_input("Requires Car Parking? (0/1)", min_value=0, max_value=1, value=0)
    room_type_reserved = st.text_input("Room Type (e.g. Room_Type 1)")
    lead_time = st.number_input("Lead Time (days)", min_value=0, value=30)
    arrival_year = st.number_input("Arrival Year (e.g. 2017)", min_value=2000, value=2017)
    arrival_month = st.number_input("Arrival Month", min_value=1, max_value=12, value=6)
    arrival_date = st.number_input("Arrival Date", min_value=1, max_value=31, value=15)
    market_segment_type = st.text_input("Market Segment (e.g. Online)")
    repeated_guest = st.number_input("Repeated Guest? (0/1)", min_value=0, max_value=1, value=0)
    no_of_previous_cancellations = st.number_input("Previous Cancellations", min_value=0, value=0)
    no_of_previous_bookings_not_canceled = st.number_input("Previous Non-Canceled Bookings", min_value=0, value=0)
    avg_price_per_room = st.number_input("Avg. Price per Room (€)", min_value=0.0, value=75.0)
    no_of_special_requests = st.number_input("Special Requests", min_value=0, value=0)

    submitted = st.form_submit_button("Predict")

if submitted:
    input_data = {
        "no_of_adults": no_of_adults,
        "no_of_children": no_of_children,
        "no_of_weekend_nights": no_of_weekend_nights,
        "no_of_week_nights": no_of_week_nights,
        "type_of_meal_plan": type_of_meal_plan,
        "required_car_parking_space": required_car_parking_space,
        "room_type_reserved": room_type_reserved,
        "lead_time": lead_time,
        "arrival_year": arrival_year,
        "arrival_month": arrival_month,
        "arrival_date": arrival_date,
        "market_segment_type": market_segment_type,
        "repeated_guest": repeated_guest,
        "no_of_previous_cancellations": no_of_previous_cancellations,
        "no_of_previous_bookings_not_canceled": no_of_previous_bookings_not_canceled,
        "avg_price_per_room": avg_price_per_room,
        "no_of_special_requests": no_of_special_requests
    }

    df = pd.DataFrame([input_data])
    prediction = model.predict(df)[0]
    proba = model.predict_proba(df)[0][prediction]
    label = "Canceled" if prediction == 1 else "Not Canceled"

    st.success(f"Prediction: **{label}**  \nConfidence: **{proba:.2%}**")