# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DhO31vWnji_dNchYOjSVkif5tXF70Tna
"""

import streamlit as st
import pandas as pd
import pickle

@st.cache_resource
def load_model():
    with open("best_model_pipeline.pkl", "rb") as f:
        return pickle.load(f)

model = load_model()

st.set_page_config(page_title="Hotel Booking Prediction", layout="centered")
st.title("Hotel Booking Cancellation Prediction")

with st.form("booking_form"):
    no_of_adults = st.slider("Number of Adults", 0, 4, 2)
    no_of_children = st.slider("Number of Children", 0, 10, 0)
    no_of_weekend_nights = st.slider("Weekend Nights", 0, 7, 1)
    no_of_week_nights = st.slider("Week Nights", 0, 17, 2)
    type_of_meal_plan = st.selectbox("Meal Plan", ["Meal Plan 1", "Meal Plan 2", "Meal Plan 3", "Not Selected"])
    required_car_parking_space = st.selectbox("Requires Car Parking?", [0, 1])
    room_type_reserved = st.selectbox("Room Type", [
        "Room_Type 1", "Room_Type 2", "Room_Type 3",
        "Room_Type 4", "Room_Type 5", "Room_Type 6", "Room_Type 7"
    ])
    lead_time = st.slider("Lead Time (days)", 0, 450, 30)
    arrival_year = st.selectbox("Arrival Year", [2017, 2018])
    arrival_month = st.slider("Arrival Month", 1, 12, 6)
    arrival_date = st.slider("Arrival Date", 1, 31, 15)
    market_segment_type = st.selectbox("Market Segment", [
        "Online", "Offline", "Corporate", "Complementary", "Aviation"
    ])
    repeated_guest = st.selectbox("Repeated Guest?", [0, 1])
    no_of_previous_cancellations = st.slider("Previous Cancellations", 0, 20, 0)
    no_of_previous_bookings_not_canceled = st.slider("Previous Non-Canceled Bookings", 0, 60, 0)
    avg_price_per_room = st.slider("Avg. Price per Room (€)", 0.0, 550.0, 75.0)
    no_of_special_requests = st.slider("Special Requests", 0, 5, 0)

    submitted = st.form_submit_button("Predict")

if submitted:
    input_data = {
        "no_of_adults": no_of_adults,
        "no_of_children": no_of_children,
        "no_of_weekend_nights": no_of_weekend_nights,
        "no_of_week_nights": no_of_week_nights,
        "type_of_meal_plan": type_of_meal_plan,
        "required_car_parking_space": required_car_parking_space,
        "room_type_reserved": room_type_reserved,
        "lead_time": lead_time,
        "arrival_year": arrival_year,
        "arrival_month": arrival_month,
        "arrival_date": arrival_date,
        "market_segment_type": market_segment_type,
        "repeated_guest": repeated_guest,
        "no_of_previous_cancellations": no_of_previous_cancellations,
        "no_of_previous_bookings_not_canceled": no_of_previous_bookings_not_canceled,
        "avg_price_per_room": avg_price_per_room,
        "no_of_special_requests": no_of_special_requests
    }

    df = pd.DataFrame([input_data])
    prediction = model.predict(df)[0]
    proba = model.predict_proba(df)[0][prediction]
    label = "Canceled" if prediction == 1 else "Not Canceled"

    st.success(f"Prediction: **{label}**  \nConfidence: **{proba:.2%}**")