# -*- coding: utf-8 -*-
"""inference

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GiisVYNhpATk1UJxYM7Gl0-QTxN39a74
"""

import pickle
import numpy as np
import pandas as pd

with open('best_model.pkl', 'rb') as file:
    model = pickle.load(file)

columns = ['no_of_adults', 'no_of_children', 'no_of_weekend_nights', 'no_of_week_nights',
           'type_of_meal_plan', 'required_car_parking_space', 'room_type_reserved',
           'lead_time', 'arrival_year', 'arrival_month', 'arrival_date',
           'market_segment_type', 'repeated_guest', 'no_of_previous_cancellations',
           'no_of_previous_bookings_not_canceled', 'avg_price_per_room', 'no_of_special_requests']

def predict_booking_status(input_data):
    df = pd.DataFrame([input_data], columns=columns)

    cat_cols = df.select_dtypes(include='object').columns
    df[cat_cols] = encoder.transform(df[cat_cols])

    prediction = model.predict(df)
    return prediction[0]